name: onboarding_models
version: 0.0.9
description: Digicy Onboarding models and services
environment:
  sdk: '>=1.24.2 <2.0.0'
dependencies:
  angular: "4.0.0"
  angular_components: "^0.6.0"
  fo_components:
    path: ../../Visurus/FoComponents
  http: ^0.11.3+14
  intl: ^0.15.0
  vi_auth_client:
    path: ../../Visurus/ViAuthClient

transformers:
  - angular

web:
  compiler:
    debug: dartdevc